name: Jekyll site CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: docker://ruby:latest
    - name: Build the site
      run: |
        gem update --system
        gem install bundler
        bundle install --path vendor/bundle
        bundle exec jekyll build
        mkdir dist
        tar -czvf dist/package-${{ github.sha }}.tar.gz -C _site .
