name: Jekyll site CI

on: [push]
jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest
    container:
      image: ruby:latest
      volumes: 
        - ${{ github.workspace }}:/srv/jekyll
        - ${{ github.workspace }}/_site:/srv/jekyll/_site
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
      - name: Build site
        run: |
          gem update --system
          gem install bundler
          bundle install --path vendor/bundle
          bundle exec jekyll build
          mkdir dist
          # tar -czvf dist/package-${{ github.sha }}.tar.gz -C _site .
          ls .
      - name: Deploy to web        
        run: |
          uses: AEnterprise/rsync-deploy@v1.0
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOYMENT_KEY }}
          ARGS: "-e -e"
          SERVER_PORT: 22
          FOLDER: "_site"
          SERVER_IP: team12-19.studenti.fiit.stuba.sk
          USERNAME: bitbucket
          SERVER_DESTINATION: /var/www/html

