name: Jekyll site CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the site in the jekyll/builder container
      run: |
        docker run -v ${{ github.workspace }}:/build -v ${{ github.workspace }}/_site:/build/_site jekyll/builder:latest /bin/bash -c "chmod 777 /build && jekyll build --future"
        mkdir dist
        tar -czvf dist/package-${{ github.sha }}.tar.gz -C _site /srv/jekyll/_site
