name: Jekyll site CI

on: [push]
jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest
    container:
      image: ruby:latest
      volumes: 
        - ${{ github.workspace }}:/srv/jekyll
        - ${{ github.workspace }}/_site:/srv/jekyll/_site
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
      - name: Build site
        run: |
          gem update --system
          gem install bundler
          bundle install --path vendor/bundle
          bundle exec jekyll build
          mkdir dist
          tar -czvf dist/package-${{ github.sha }}.tar.gz -C _site .
          ls .
      - name: Deploy to web        
        run: |
          mkdir upload
          tar -xf dist/package-${{ github.sha }}.tar.gz -C upload
          apk update && apk add openssh rsync
          rsync -a  -e "ssh -o StrictHostKeyChecking=no" --delete upload/ bitbucket@team12-19.studenti.fiit.stuba.sk:/var/www/html-${{ github.sha }}
          ssh -o StrictHostKeyChecking=no bitbucket@team12-19.studenti.fiit.stuba.sk "rm -r /var/www/html"
          ssh -o StrictHostKeyChecking=no bitbucket@team12-19.studenti.fiit.stuba.sk "mv '/var/www/html-${{ github.sha }}' '/var/www/html'"

