name: Jekyll site CI

on: [push]
jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest
    container:
      image: ruby:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
      - name: Build site
          gem update --system
          gem install bundler
          bundle install --path vendor/bundle
          bundle exec jekyll build
          mkdir dist
          tar -czvf dist/package-${{ github.sha }}.tar.gz -C _site .
