name: Jekyll site CI

on: [push]
jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest
    steps:
    - name: GHA Jekyll Build
      uses: gha-utilities/jekyll-build@v0.0.1
      with:
        # Relative path that source files for Jekyll to build exsist
        # Path where compiled site files should be saved to
        destination: /site
